### ISSUE TITLE
It doesn't show up

### ISSUE THREAD

**Issue by dermamred** [linux-man/caja-mediainfo-tab#1] opened 2018-06-13 16:28 UTC
Caja 1.14.2

Installed from PPA, the extension doesn't show up as tab in Properties > Tab.
![schermata del 2018-06-13 18-27-46](https://user-images.githubusercontent.com/36823096/41364661-957dcbb8-6f37-11e8-87a4-572d3d99824d.png)

**Comment by linux-man** [comment] 2018-06-13 16:53
Have you restarted Caja (I think you can do it with console caja --quit) or rebooted your system?

**Comment by dermamred** [comment] 2018-06-13 17:11
I restarted Caja twice but nothing... now I gonna try rebooting.

**Comment by dermamred** [comment] 2018-06-13 17:17
Even rebooting it still doesn't show up anywhere but in Preferences > Extensions (tab) > Python: caja-mediainfo-tab... but enable/disable option does nothing.

**Comment by linux-man** [comment] 2018-06-13 18:44
OK. Since I'm using Mint 19 Beta, I tested the PPA with a 18.3 Live CD. It works (and that's bad for you).
Can you please run on console
`caja --quit && CAJA_DEBUG=y caja --no-desktop`
just to see if anything shows up on the console at start or when you open file properties?
Finally the dumb questions : have you tried more media files (like videos)? Is TBT.mp3 a valid mp3 file? Sorry to ask, but doing remote debugging is complicated.

**Comment by dermamred** [comment] 2018-06-13 19:26
Here's the debug log...

`Initializing caja-open-terminal extension
** Message: Initializing gksu extension...
/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py:50: RuntimeWarning: You have imported the Gtk 2.0 module.  Because Gtk 2.0 was not designed for use with introspection some of the interfaces and API will fail.  As such this is not supported by the pygobject development team and we encourage you to port your app to Gtk 3 or greater. PyGTK is the recomended python module to use with Gtk 2.0
  warnings.warn(warn_msg, RuntimeWarning)
sys:1: PyGIWarning: Caja was imported without specifying a version first. Use gi.require_version('Caja', '2.0') before import to ensure that the right version gets loaded.

** (caja:18800): WARNING **: Invalid borders specified for theme pixmap:
        /home/dermadream/.themes/Breezed/gtk-2.0/Buttons/button-combo-gray-pressed.png,
borders don't fit within the image
Traceback (most recent call last):
  File "/usr/share/caja-python/extensions/caja-mediainfo-tab.py", line 69, in get_property_pages
    self.builder.add_from_string(GUI)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 462, in add_from_string
    return Gtk.Builder.add_from_string(self, buffer, length)
GLib.Error: gtk-builder-error-quark: <input>: required gtk+ version 3.0, current version is 2.24 (7)
Traceback (most recent call last):
  File "/usr/share/caja-python/extensions/caja-mediainfo-tab.py", line 69, in get_property_pages
    self.builder.add_from_string(GUI)
  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 462, in add_from_string
    return Gtk.Builder.add_from_string(self, buffer, length)
GLib.Error: gtk-builder-error-quark: <input>: required gtk+ version 3.0, current version is 2.24 (7)`


...tried w/ 2 iles, as U can see from the 2 Tracebacks, a MP3 and a video .WEBM, but nothing, not considering errors regarding issu w/ theme I'm using... both files I tried are files that are not corrupted or "unknown".


Don't worry... I know that debugging is complicated and how much difficult is finding the "solution".

**Comment by linux-man** [comment] 2018-06-13 20:50
I should have paid attention to your caja version. You're still using Mint 18.0. The problem is that your Caja was build against Gtk 2.
I explored a little and found out that only Mint 18.2 - Caja 1.18 was build with full Gtk 3 support.
To make it work I'll need to change some incompatible design objects - specifically GtkGrid - that don't exist on Gtk 2.
It will take some time.

**Comment by linux-man** [comment] 2018-06-14 03:46
I can't achieve the same layout and behaviour with GtkBoxes. This is the closest I can get.
Can you try it? Extract and copy the file to /usr/share/caja-python/extensions/.
[caja-mediainfo-tab.py.zip](https://github.com/linux-man/caja-mediainfo-tab/files/2100729/caja-mediainfo-tab.py.zip)

**Comment by dermamred** [comment] 2018-06-14 15:31
It works!

Tried w/ 2 files, one MP3 (...as shown in the attached screenshot) and one AVI.

![schermata del 2018-06-14 17-24-51](https://user-images.githubusercontent.com/36823096/41422230-c36d6620-6ff8-11e8-9a4b-0774d433e93a.png)


P.S.: I figured that the issue had to deal w/ Caja version I'm using having take a peek in ".py".

**Comment by linux-man** [comment] 2018-06-14 16:51
Good. Since you find different Caja versions on Xenial base, and the layout is not exactly the same, I'm not replacing the original caja-mediainfo-tab. Instead I'm updating the PPA with a new package named caja-mediainfo-tab-gtk2 for those of you who still use Caja < 1.18.

**Comment by linux-man** [comment] 2018-06-16 14:31
Closing if nothing comes up...

**Closed as completed by linux-man** 2018-06-16 14:31 UTC

**Comment by dermamred** [comment] 2018-06-16 14:47
Thanx.
